// <auto-generated />
namespace AfricanMagicSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _19OctoberImportedOldDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_19OctoberImportedOldDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202010191659459_19-October-ImportedOldDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
